---
swarm_force_init: false

psql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66656433383164373538376665356134646331323661336238383239346339653034623130616266
          6238643632636663356431393632386434666431663565640a666333396263393165373737653231
          66633964393163626163623138336332396430646464346261653961396333666233633634343865
          3732376437343333640a393665316133646266356232613061343661316363326465643431383339
          37376666306463316435343665666261386532356361303437313365373734636431