---
ssh_public_key_main: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62313037363733653438306463653731333262363734613931356263663563646161326132353264
          3734316330346439313232303030306235303761343639640a613063326261353137383937326130
          31323332393864616466313133643336363165346637376266623138356230653635393465363861
          3163646531633032660a386339613061663365396330633437643466376431316436313137353565
          61653832386332616333626561633665613764613331363436373038623339316135303166396233
          31623366363034373761653937346134393131616338353834656636333162386134613162353038
          30623834636663316165336565306566373438313535313563613736336434306534633432343036
          34313531396230316163383232343731366433633737343237333464356662623931393237663438
          64356432663633633866636561383661613265373539636232613836306131623364363439373862
          6131326134353738303065613937353436303338346236633431

admin_users:
  - name: admin-1
    ssh_public_key: "{{ ssh_public_key_main }}"
  - name: admin-2
    ssh_public_key: "{{ ssh_public_key_main }}"
  - name: admin-3
    ssh_public_key: "{{ ssh_public_key_main }}"

technical_users:
  - name: ansible
    ssh_public_key: "{{ ssh_public_key_main }}"
  - name: autodeploy
    ssh_public_key: "{{ ssh_public_key_main }}"
