---
- name: Create admin users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/bash
    create_home: true
    groups: "sudo"
    append: true
    state: present
  loop: "{{ admin_users }}"

- name: Create technical users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/bash
    create_home: true
    groups: "sudo"
    append: true
    state: present
  loop: "{{ technical_users }}"

- name: Add ssh authorized keys admin users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_public_key }}"
    state: present
    exclusive: true
  loop: "{{ admin_users }}"

- name: Add ssh authorized keys technical users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_public_key }}"
    state: present
    exclusive: true
  loop: "{{ technical_users }}"

- name: Disable SSH password auth and root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: true
  loop:
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: 'AuthenticationMethods', line: 'AuthenticationMethods publickey' }
  notify: restart ssh
