---
all:
  children:
    mobilepark:
      children:
        managers:
          hosts:
            mobilepark1:
        workers:
          hosts:
            mobilepark2:
            mobilepark3:
      hosts:
        mobilepark1:
          ansible_user: ansible
          ansible_host: 192.168.7.241
          ansible_private_key_file: ~/.ssh/homelab_id25519
        mobilepark2:
          ansible_user: ansible
          ansible_host: 192.168.7.242
          ansible_private_key_file: ~/.ssh/homelab_id25519
        mobilepark3:
          ansible_user: ansible
          ansible_host: 192.168.7.243
          ansible_private_key_file: ~/.ssh/homelab_id25519
